### PR TITLE
fix: new offsets b20230313

### PR DESCRIPTION
**Pull request by KotRikD**

### CODE REVIEW

**Comment by KotRikD** [comment]
Anyone who need build with fixes.

Blackshark kinda ignores me last time, sooo...

https://baka-ero.kotworks.cyou/new/gosumemory_b20230313.exe

**Comment by KotRikD** [comment]
Closes #178

**Review by Fefferoni02 — COMMENTED** [review]
KotRikD:feature/new_offsets_2

**Comment by Sclafus** [comment]
Hi @l3lackShark , would it be possible to make a new patch release for this and also include Linux executable? A random .exe from a random website is not the best.

**Pull request merged**
